### ISSUE TITLE
PILOTSIZE nodes

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#42]
Why is the PILOTSIZE in cores and not nodes when the pbs script uses nodes?

**Comment by andre-merzky** [comment]
RP also works on clusters and batch systems where resources are counted in cores, not nodes, and specifically also where partial nodes can be used.  Also, we wanted to have the same resource type for the pilot and for the compute units - because otherwise the user would need to know the node size when specifying CUs to match the pilot size.

**Comment by euhruska** [comment]
Makes sense
